version: '3.1'
services:
  app:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGODB_HOSTNAME: mongo
      DEPLOY: Production
    networks:
      - backend
    depends_on:
    - mongo
  
  mongo:
    image: mongo
    networks:
      - backend
      
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge



      